config/routes.rb
Rails.application.routes.draw do

  api_version(:module => "V1", :path => {:value => "v1"}, :default => true) do
    resources :user
  end
  get 'session/new'

  resources :users
  resources :micropots
  resources :like_pros

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'users'   =>'users'
  get 'signup'  => 'users#new'
  get 'edit'    => 'users#edit'
  get 'login'   => 'session#new'
  post 'login'   => 'session#create'
  get 'logout' => 'session#destroy'

  put 'like'    => 'like_pros#update'
  put 'unlike'  => 'like_pros#update'

end

app/models/micropot.rb
class Micropot < ActiveRecord::Base
  belongs_to :user
  has_many :like_pro
  has_many :comment ,dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

  mount_uploader :picture , PictureUploader


  def alllike
  	like_pro
  end



  def checkliked(user_id,micropot_id)
  	@micropot = Micropot.find_by(:id => micropot_id)
 	@is_like = @micropot.like_pro.find_by(:user_id => user_id)
  	# @micropot = Micropot.find_by(:user_id => user_id)
  	return @is_like.nil?
  end

end

app/controllers/micropots_controller.rb
class MicropotsController < ApplicationController
  include SessionHelper
	before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def create
    @micropot = current_user.micropots.build(micropot_params)
    if @micropot.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      # @feed_items = []              # why we need this
      render 'static_pages/home'
    end
  end

  def destroy
    @micropot.destroy
    flash[:success] = "Micropot deleted"
    redirect_to request.referrer || root_url
  end

  def update
      @micropot = Micropot.find(params[:id])
      object = Like_pros.new(:micropot_id =>@micropot, :user_id =>@current_user)
      object.save
      redirect_to @current_user
  end

  def show

  end


private
	def micropot_params
		params.require(:micropot).permit(:content)
	end 

  def correct_user
    @micropot = current_user.micropots.find_by(id: params[:id])
    redirect_to root_url if @micropot.nil?
  end

  def micropot_params
    params.require(:micropot).permit(:content, :picture)
  end

end

app/helpers/micropots_helper.rb
module MicropotsHelper
end

app/views/micropots/_micropot.html.erb
<li id="micropot-<%= micropot.id %>">
    <span class="content">
    <%= image_tag micropot.picture.url if micropot.picture? %>
    <br>
    <%= micropot.content %>

  </span>
  <br>
  <span class="timestamp">

    Posted <%= time_ago_in_words(micropot.created_at) %> ago.
    <% if current_user.nil? %>
    <% else %>
    <br>
       <%= micropot.like_pro.count %> likes 
       <br>
       <% if getreferuser.nil?%>
       <% else %>
        <% if micropot.checkliked(current_user.id,micropot.id) %>
        <%= link_to "likes", like_path(:id => micropot.id ,:current_user => current_user.id ,:is_like => "1",:refer_user => getreferuser) ,method: :put %>
        <% else %>
        <%= link_to "unlike", unlike_path(:id => micropot.id ,:current_user => current_user.id,:is_like => "0",:refer_user => getreferuser ) ,method: :put %>
        <% end %>
        <% end %>
      <%= link_to "delete", micropot, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>