config/routes.rb
Rails.application.routes.draw do

  api_version(:module => "V1", :path => {:value => "v1"}, :default => true) do
    resources :user
  end
  get 'session/new'

  resources :users
  resources :micropots
  resources :like_pros

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'users'   =>'users'
  get 'signup'  => 'users#new'
  get 'edit'    => 'users#edit'
  get 'login'   => 'session#new'
  post 'login'   => 'session#create'
  get 'logout' => 'session#destroy'

  put 'like'    => 'like_pros#update'
  put 'unlike'  => 'like_pros#update'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "BlogSystem", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Help",   help_path %></li>
            <li><%= link_to "Log in", login_path %></li>
            <li><%= link_to "Signup", signup_path %></li>
            <li><%= link_to "logout", logout_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>